Allow non-burning stars in MT
POSYDON-code/POSYDON-public pull request #206
Opened 2023-11-30 15:47 UTC by astroJeff

We have added code that allows non burning stars to enter mass transfer without failing immediately. @celiotine will test this. Addresses Issue #205.

2023-12-01 21:19 UTC, celiotine requested changes
I tested these changes and the issue was not fixed. Looking more closely at the code, there are a couple problems:
1) The updated logic in `infer_mass_transfer_case` is not quite correct. It checks for substrings that also exist in the `non_burning` states first, so it enters these statements, finds no MT case, and returns undetermined. Moving the check for `MT_CASE_NONBURNING` first fixes this issue, and seems to fix the overarching issue for most systems.
1) I think the function `cumulative_mass_transfer_string` needs to include the new `MT_CASE_NONBURNING`?

2023-12-05 17:15 UTC, celiotine commented
I have looked more thoroughly at the "fixed" tracks and most (>90%) of the stars undergoing `stripped_He_non_burning` look this, which seems odd to me:
<img width="779" alt="Screen Shot 2023-12-05 at 11 13 30 AM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/84a3dffd-03d0-4b1b-918f-bb8e18f81c55">
i.e. they go to `initial_RLOF` and then end.

2023-12-07 17:54 UTC, celiotine commented
A nice example of a corrected track after fixing w/ my comment above:
<img width="660" alt="Screen Shot 2023-12-07 at 11 54 16 AM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/217c16fe-d3f7-4937-b166-ea05a3b1bdc3">

2023-12-14 15:39 UTC, celiotine approved these changes

2024-01-18 15:30 UTC, astroJeff commented
Update (Jan 18): We need one more test of this. @ezapartas and @dimsour94 to test

2024-01-18 15:41 UTC, kkovlakas approved these changes

2024-01-24 17:24 UTC, ezapartas approved these changes

2024-01-25 14:50 UTC, dimsour94 approved these changes

2024-01-25 15:33 UTC, merged