Rewriting magnetic braking physics into its own file
POSYDON-code/POSYDON-public pull request #75
Opened 2023-05-18 22:07 UTC by astroJeff

2023-05-18 23:08 UTC, sgossage commented on posydon/binary_evol/DT/magnetic_braking.py
> +    K = 1.4e30 * const.secyer**2 / (const.msol * const.rsol**2)
```suggestion
    K = -1.4e30 * const.secyer**2 / (const.msol * const.rsol**2)
```

Right now the torque in M15 would evaluate to positive. The constant K should have a negative sign

2023-05-18 23:09 UTC, sgossage commented on posydon/binary_evol/DT/magnetic_braking.py
> +    c = 3e41 / (const.msol * const.rsol**2)
```suggestion
    c = -3e41 / (const.msol * const.rsol**2)
```

The same as above for M15, the G18 torque currently evaluates to positive. This constant should have a negative to correct that.

2023-05-18 23:12 UTC, sgossage requested changes
The M15 and G18 prescriptions need a negative sign in their torques (which I've made comments on), otherwise I think this looks good.

2023-05-25 14:58 UTC, sgossage approved these changes
This looks good to me, thanks Jeff

2023-07-20 14:07 UTC, sgossage commented on posydon/binary_evol/DT/magnetic_braking.py
> +        -3.8e30 * (const.rsol**2 / const.secyer)
My mistake, here's a typo: this should be -3.8e-30 (as in Rappaport, Verbunt, and Joss) not -3.8e30

2023-07-20 14:07 UTC, sgossage commented on posydon/binary_evol/DT/magnetic_braking.py
> +        -3.8e30 * (const.rsol**2 / const.secyer)
My mistake, here's a typo: this should be -3.8e-30 (as in Rappaport, Verbunt, and Joss) not -3.8e30

2024-03-28 14:08 UTC, mkruckow commented
Update (March 28): @astroJeff , it looks like stalling, hence please get back to work on it or consider to close the PR.

2025-09-02 16:32 UTC, astroJeff commented
superseded by #675

2025-09-02 16:32 UTC, closed without merging